pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/Audrey-Okumu/alx-backend-python.git', credentialsId: 'github-credentials'
            }
        }

        stage('Install dependencies') {
            steps {
                echo 'Installing dependencies from messaging_app/requirements.txt...'
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                echo 'Running pytest and generating report...'
                sh '''
                    . venv/bin/activate
                    pytest --maxfail=1 --disable-warnings --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully.'
        }
        failure {
            echo '❌ Pipeline failed. Please check logs.'
        }
    }
}
