pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                git url: 'https://github.com/Audrey-Okumu/alx-backend-python.git', branch: 'main'
            }
        }

        stage('Install dependencies') {
            steps {
                dir('messaging_app') {
                    echo 'Installing Python dependencies...'
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('messaging_app') {
                    echo 'Running tests using pytest...'
                    sh '''
                        . venv/bin/activate
                        pytest --maxfail=1 --disable-warnings --junitxml=report.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
