apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-web-blue
  labels:
    app: messaging-web
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-web
      version: blue
  template:
    metadata:
      labels:
        app: messaging-web
        version: blue
    spec:
      containers:
        - name: messaging-web
          image: messaging_web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: messaging_db
            - name: DEBUG
              value: "1"
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings