version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_SSL_MODE=DISABLED    
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  web:
    build: .
    container_name: messaging_web
    command: >
      bash -c "
      echo ' Waiting for MySQL...' &&
      until mysqladmin ping -h db --silent; do
        sleep 2
      done &&
      echo '✅ MySQL is ready! Running migrations...' &&
      python manage.py migrate &&
      echo '🚀 Starting Django server...' &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
